CXX = g++
CXXFLAGS = -g -Wno-write-strings
LDFLAGS = -g

include config.makefile

SOURCES = $(wildcard *.cpp) $(wildcard Magicengine/*.cpp)
OBJECTS = $(patsubst %.cpp,%.o,$(SOURCES))
GENERATED = test doxygen $(OBJECTS)

all: test .gitignore

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c -o $@ $?

test: $(OBJECTS)
	$(CXX) -o $@ $? $(LDFLAGS)

doku:
	doxygen doxygen
	scp -r Doku/html/* sven@blizzer-gaming.de:/var/www/doku
	rm -r Doku/

clean:
	rm -fv $(GENERATED)

.gitignore:
	echo '# FILE IS GENERATED BY MAKE - DO NOT EDIT' > $@
	echo '/config.makefile'
	for file in $(GENERATED) ; do \
		echo /$$file >> $@ ; \
	done

.PHONY: all clean
