CXX = g++
CXXFLAGS = -g -Wno-write-strings
LDFLAGS = -g

PACKAGES = sdl2 sdl2_image
CXXFLAGS += `pkg-config --cflags $(PACKAGES)`
LDFLAGS  += `pkg-config --libs $(PACKAGES)`

SOURCES = $(wildcard *.cpp) $(wildcard Magiengine/*.cpp)
OBJECTS = $(patsubst %.cpp,%.o,$(SOURCES))
GENERATED = test .gitignore $(OBJECTS)

all: test .gitignore

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c -o $@ $?

test: $(OBJECTS)
	$(CXX) -o $@ $? $(LDFLAGS)

clean:
	rm -fv $(GENERATED)

.gitignore:
	echo '# FILE IS GENERATED BY MAKE - DO NOT EDIT' > $@
	for file in $(GENERATED) ; do \
		echo /$$file >> $@ ; \
	done

.PHONY: all clean
